### ISSUE TITLE
Typo in require fs-ext

### ISSUE THREAD

**Issue by sidthekidder** [PencilCode/pencilcode#104]
Hi,
In https://github.com/PencilCode/pencilcode/blob/master/server/load.js#L2 , the module 'fs-ext' is required. This dependency gave me an error during npm install due to which I discovered that replacing it with 'fs' worked without any error. Even in https://github.com/PencilCode/pencilcode/blob/master/server/save.js#L2 the 'fs' module is required, and 'fs-ext' doesn't seem to use any special methods not in 'fs', and it isn't used anywhere else, so it may be a typo.

**Comment by xinan** [comment]
I notice that in the package.json, the version for fs-ext is stated as 'latest', but npm keeps trying to install an old version which will fail to install. Then I ran "npm update" and the issue gets resolved. I'm a bit confused here. Can someone explain this to me? Thanks! 
(npm and node are latest version)

**Comment by xinan** [comment]
Oh I've found that it is because the npm-shrinkwrap file locked the versions of the dependencies. And somehow the fs-ext@0.3.2 can't be installed on my machine. I removed the lock and it works fine now.

**Comment by hussien89aa** [comment]
To fix that go to package.json
and change there dependencies here
"fs-ext": "latest",
"fs-extra": "latest"

Then run this command from the terminal
npm install --save fs-extra
npm install --save fs-ext

Problem is fixed
