### ISSUE TITLE
Pencil Code is incompatible with Node v0.12.x

### ISSUE THREAD

**Issue by davidbau** [PencilCode/pencilcode#115]
There are several reasons we want to upgrade to node v0.12.x:
- We should stay current with the latest node for stability.
- There is improved support for multiprocess servers.

Unfortunately, pencilcode does not currently work with node v.0.12.x.  Incompatibilities are probably something relatively simple; we should investigate and upgrade.

**Comment by rishabhc** [comment]
This issue has been resolved. We should close it.
