### ISSUE TITLE
Development Server Issue with Pencil Code

### ISSUE THREAD

**Issue by aboss1** [PencilCode/pencilcode#141]
When running the devserver on the latest branch, code runs smoothly, but following 404 errors keep appearing: 
![screen shot 2015-06-30 at 4 13 28 pm](https://cloud.githubusercontent.com/assets/10790729/8441032/d7ba1c44-1f43-11e5-91aa-611063a7795f.png)

**Comment by davidbau** [comment]
This should be fixed by pull #147.  Can you review that (small) pull request?

**Comment by davidbau** [comment]
Should be fixed now!
