### ISSUE TITLE
Infinite speed programs get interrupted after 3 seconds.

### ISSUE THREAD

**Issue by xinan** [PencilCode/pencilcode#157]
Programs with `speed Infinity` would usually freeze for a while and output the result instantly. Sometimes the program might take a bit longer and eventually terminates. 

Our recent implementation (96aa1f872062839074071a10ace8c56c756ae9b9) to prevent programs from being stuck in infinite loops sets the stuck timeout to `3000ms`, which is pretty fine for most programs. However, it interrupts some programs with `speed Infinity` too early. Maybe we should set a longer timeout for this special kind of programs?

![Infinite speed programs get interrupted unexpectedly](https://cloud.githubusercontent.com/assets/2834397/8651250/5c384c3c-29aa-11e5-9474-a5632db92e0c.png)

**Comment by davidbau** [comment]
One thing to do is to watch trace events.  If a tight loops is not doing anything interesting (e.e.,g not trying to move the turtle), we can stop in in 3 seconds.

But we can give more time when it is doing something nontrivial.

I'll add this logic.

**Comment by xinan** [comment]
Thanks! :smile:

**Comment by davidbau** [comment]
Fixed now!
