### ISSUE TITLE
HTML code will not switch to BLOCKS mode

### ISSUE THREAD

**Issue by MichaelEason** [PencilCode/pencilcode#194]
Simple HTML code will not switch to BLOCKS mode.

Error message is: 
"Oops, the computer could not show blocks. It says:this.model.getLinesToParent is not a function"

The HTML code and error is shown below:
![image](https://cloud.githubusercontent.com/assets/9910523/9564145/4eea0022-4e6a-11e5-8ed8-94549406ddcc.png)

Any idea what is wrong?

I have copied the code from PencilCode into Notepad, then copied it back from Notepad into a new PencilCode document, and still can't switch to BLOCKS mode.

I retyped the code directly into a new PencilCode document and had no problem switching to BLOCKS mode.

**Comment by davidbau** [comment]
Sounds like a bug!  Can you send a link to the URL or the exact HTML text
that you used?  (I know you sent a screenshot, but if I just type it in, I
may miss spaces or other invisible characters.)

**Comment by MichaelEason** [comment]
http://shalynn.pencilcode.net/edit/shalynntaboutme.html and http://shalynn.pencilcode.net/edit/shalynntindexi.html

**Comment by MichaelEason** [comment]
The code belongs to one of my students.

If you copy the code from either link and paste it into a blank .html file in your PencilCode account, it should fail to switch to BLOCKS mode just like it does for me (and the student). I have twenty other students using PencilCode without this problem.

**Comment by davidbau** [comment]
Thanks Michael.  I've opened up this issue - we'll investigate and get it
fixed.

https://github.com/droplet-editor/droplet/issues/126

David

**Comment by davidbau** [comment]
The fix for this bug has been pushed!
